name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - DrJanDuffy

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! 🐛
        
        Please fill out the form below to help us understand and fix the issue.

  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: Your email or preferred contact method
      placeholder: your-email@example.com
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (Minor inconvenience)
        - Medium (Affects functionality)
        - High (Blocks core functionality)
        - Critical (Site down/broken)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g. Windows 10, macOS 12, Ubuntu 20.04]
        - Browser: [e.g. Chrome 95, Firefox 94, Safari 15]
        - Node.js version: [e.g. 18.0.0]
        - Project version: [e.g. 1.0.0]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or error messages
      placeholder: Add any other context about the problem here...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
